version: "3.8"
services:
  db:
    image: postgres:13.1-alpine
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nonesecure+github@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
networks:
  postgres:
    driver: bridge
volumes:
  local_pgdata:
  pgadmin-data: